trigger:
  - main

variables:
  dockerHubConnection: 'docker-hub-conn'  # your Docker service connection name
  imageRepository: 'satheesh2003/flask-devops-app'
  imageTag: 'v5'

pool:
  vmImage: 'ubuntu-latest'  # ✅ Use Microsoft-hosted agent for Docker

steps:
  - task: Docker@2
    displayName: Build and Push to Docker Hub
    inputs:
      command: buildAndPush
      containerRegistry: $(dockerHubConnection)
      repository: $(imageRepository)
      tags: |
        $(imageTag)

  - script: echo "🎉 Build & push successful!"
    displayName: Done

