trigger:
  - main

variables:
  dockerHubConnection: 'docker-hub-conn'  # your Docker service connection name
  imageRepository: 'satheesh2003/flask-devops-app'
  imageTag: 'v5'

pool:
  name: Default
  demands:
    - Agent.Name -equals SATHEESH

steps:
  - task: Docker@2
    displayName: Build and Push to Docker Hub
    inputs:
      command: buildAndPush
      containerRegistry: docker-hub-conn 
      repository: $(imageRepository)
      tags: |
        $(imageTag)

  - script: echo "🎉 Build & push successful!"
    displayName: Done

