trigger:
  - main

pool:
  name: Default
  demands:
    - Agent.Name -equals SATHEESH

variables:
  imageName: satheesh2003/flask-devops-app
  imageTag: v4

steps:
  - task: Docker@2
    displayName: Build and Push to Docker Hub
    inputs:
      command: buildAndPush
      containerRegistry: 'dummy'  # won't be used since we logged in manually
      repository: $(imageName)
      tags: |
        $(imageTag)

